# Generated by Django 3.2.3 on 2022-09-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(null=True, upload_to='home/images'),
        ),
        migrations.AddField(
            model_name='blog',
            name='sub_category',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
